USE [master]
GO

CREATE DATABASE [Vehicles]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Vehicles', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Vehicles.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Vehicles_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Vehicles_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Vehicles].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Vehicles] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Vehicles] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Vehicles] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Vehicles] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Vehicles] SET ARITHABORT OFF 
GO

ALTER DATABASE [Vehicles] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [Vehicles] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Vehicles] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Vehicles] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Vehicles] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Vehicles] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Vehicles] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Vehicles] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Vehicles] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Vehicles] SET  ENABLE_BROKER 
GO

ALTER DATABASE [Vehicles] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Vehicles] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Vehicles] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Vehicles] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Vehicles] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Vehicles] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Vehicles] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Vehicles] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Vehicles] SET  MULTI_USER 
GO

ALTER DATABASE [Vehicles] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Vehicles] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Vehicles] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Vehicles] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Vehicles] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Vehicles] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Vehicles] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Vehicles] SET  READ_WRITE 
GO


